var language = {
    nav: {
        cn: {
            home: '首页',
            goodpage: 'GoodPago',
            segura: 'Segura',
            ascces: 'SACCES'
        },
        en: {
            home: '首页',
            goodpage: 'GoodPago',
            segura: 'Segura',
            ascces: 'SACCES'
        },
        sp: {
            home: '首页',
            goodpage: 'GoodPago',
            segura: 'Segura',
            ascces: 'SACCES'
        }
    },
    goodpago: {
        cn: {
            1: '世界货币梦想的礼物',
            2: '面向全球的开发平台',
            3: 'GoodPago开放生态，面向全球商户及合作伙伴开放多种接入方式满足各种业务场景。',
            4: '本地银行发行的银行卡',
            5: '普通版银行卡',
            6: '支持多种法定和数字货币',
            7: '定制版银行卡',
            8: '支持多种法定货币和数字资产管理',
            9: '管理您的资产',
            10: '提现',
            11: '1. GoodPago的银行卡可以在全球各地的ATM上提取当地的货币；',
            12: '2. 数字货币也可以通过移动端进行提现到其他通用钱包，或者通过主流数字货币转化法定货币提现。 ',
            13: '法币与币币兑换',
            14: '1. GoodPago不但支持全球主流法币间的兑换，同时也支持主流数字货币之间的兑换或者其他的以及数字货币和各个主要货币进行兑换；',
            15: '2. GoodPago研发的数字资产交易所可以轻松的实现各类主流数字货币之间的兑换。',
            16: '转账',
            17: 'GoodPago用户可以随时随地轻松、快捷地转账给其他用户。',
            18: '充值',
            19: 'GoodPago支持线下商户POS机实时充值，线上银行转账，ATM充值，便亭充值，信用卡，支付宝，微信，银联充值及时到账 安全到账。 ',
            20: '购物付款',
            21: 'GoodPago用户可以通过移动端，POS机，银行卡 实现 等任何付款方式, 随时付款于线上线下各个商户。  ',
            22: '顶层的TPS技术',
            23: 'GoodPago的TPS高于现在主流产品，每秒可以为用户处理量高达10018的不同消息数。同时，随着技术的提升FEDPAGO的TPS也会随之提升。',
            24: 'GoodPago快速支付及转账',
            25: 'GoodPago的支付和转账功能基于最新的区块链技术，3秒内即可付款和到账，速度远快于其他区块链公链技术且保障资金安全。  ',
            26: '资产管理',
            27: 'GoodPago的用户通过区块链去中心化管理，安全保障用户资产',
            28: '高额支付互为认证',
            29: 'GoodPago用户在进行高额付款时，需要用户进行互为认证，当手机需要付款高额资金时需要用卡去认证，当用卡支付时需要手机认证，以此来保障用户资产安全。 ',
            30: '全新的征信生态',
            31: '个人征信',
            32: 'GoodPago用户在征信生态中的衣、食、住、行等可以享受免押金、免预存、先试后卖等服务，让信用变得有价值。 ',
            33: '企业征信',
            34: 'GoodPago针对企业、商户及合作伙伴建立征信系统，以分值来衡量企业的信用风险，帮助企业间、用户与企业建立优质的商业生态。 ',
            35: '出租车服务',
            36: 'GoodPago提供一站式出行平台',
            37: '保险',
            38: '通过区块链建立保险供应链金融生态',
            39: '交易所',
            40: '接入主流交易所API满足用户数字资产交易和管理',
            41: '红包',
            42: '送红包，拉近你我',
            43: '电子票务',
            44: '不需要排队收取各类票据直接云端送票 ',
            45: '电子优惠券',
            46: '不需要保管实体的优惠券',
            47: '捐款',
            48: '提供公益项目查看、捐赠、反馈的一站式服务',
            49: '金融服务',
            50: '提供金融资产管理增值服务'
        },
        en: {
            1: 'A Gift to Wold Currency Dream',
            2: 'A Global Open Payment Platform',
            3: 'Multiple open access methods for global merchants and partners to satisfy various business needs. ',
            4: 'Bank Card Issued by Local Banks',
            5: 'Classic Bank Cards',
            6: 'Support all major global currencies',
            7: 'Customized Bank Cards',
            8: 'Support all major currencies and digital assets management.  ',
            9: 'Manage Your Assets',
            10: 'Withdrawal',
            11: "1. GoodPago's card can withdraw all local currencies at ATMs around the world.",
            12: "2. Digital currency can also be cashed out to other general wallets via the mobile terminal, or through the main Streaming digital currency converts legal currency withdrawals.",
            13: 'Easy Currency Exchange',
            14: "1. GoodPago supports conversion between most of fiat currencies and exchanges among digital assets as well as exchanges between digital assets and major fiat currencies. ",
            15: "2. The Digital Assets Exchange Platform delivered by GoodPago can can easily and effectively manage your digitalassets. ",
            16: 'Transfer',
            17: 'Any GoodPago user can transfer to another user with ease, and funds are received instantly with almost no cost.',
            18: 'Deposit',
            19: "GoodPago supports merchant POS top-up, wire,  ATM deposit, Kiosk top-up, credit card, Alipay wallet, Wechat Pay, UnionPay transfer. ",
            20: 'Shopping Payment',
            21: "GoodPago users can pay to merchants, through mobile wallet, POS terminals, bank cards in real time at any supporting outlet.   ",
            22: 'Top-level TPS Technology',
            23: "GoodPago's transaction performance are higher than today's mainstream payment platforms and it can handle up to 10018 different messages per second for users. At the same time, GoodPago's will increase its performance eachtime we improve our technologies.",
            24: 'GoodPago Pays Faster',
            25: "GoodPago's payment and transfer function is based on the latest blockchain technology, In average it completes a payment roundtrip within 3 seconds, which is much faster than any other blockchain technologies and guarantees fund security.",
            26: 'Assets Management',
            27: 'Through blockchain decentralized technologies GoodPago secures their clients assets.',
            28: 'Big Amount Payments With Secondary Authentication',
            29: "When GoodPago users make big amount payment, it is required to authenticate with both physical card and wallet. When payment is done by mobile app, it is required to use card as a secondary verification tool, meanwhile, when the payment is made with card, if the amount is big, a secondary verification will be sent to the mobile app to ensure the safety of the users digital assets.",
            30: 'Brand New Credit Scoring Ecology',
            31: 'Personal Credit Scoring',
            32: "In this credit scoring ecology system, our GoodPago users can enjoy deposit-free,“pay later”services apply to all their shopping, eating, accommodations or short trips as long as they have the appropriate credit scores.",
            33: 'Corporation Credit Scoring',
            34: "GoodPago establishes a credit scoring system for businesses, merchants and partners which enables those businesses to use those scores to analyze the risk and help them to establish a better quality credit environment among their clients.",
            35: 'Taxi Service',
            36: 'GoodPago provides a one-stop travel platform',
            37: 'Insurance',
            38: 'Establish financial ecology of insurance supply chain through blockchain',
            39: 'Exchange',
            40: 'Access to all mainstream exchange’s API to satisfy users digital assets transactions and management',
            41: 'Red Packet',
            42: 'Send red packet, linking you and me      ',
            43: 'Electronic Ticketing',
            44: 'Direct tickets sell on the e-cloud and queues are no longer required for all kinds of billings, receipts ',
            45: 'Electronic Coupon',
            46: 'No need to keep paper coupons',
            47: 'Donation',
            48: 'Provide one-stop service to public welfare projects, donation and feedback',
            49: 'Financial Services',
            50: 'Servicios financieros'
        },
        sp: {
            1: 'Regalo del sueño de la moneda mundial.',
            2: 'Plataforma de desarrollo orientada globalmente.',
            3: 'GoodPago está abierto al mundo, abriendo múltiples métodos de acceso para que los comerciantes y socios globales puedan cumplir con varios escenarios comerciales.',
            4: 'Tarjeta bancaria emitida por banco local.',
            5: 'Tarjeta bancaria normal',
            6: 'Soporta múltiples divisas legales y digitales.',
            7: 'Tarjeta bancaria personalizada',
            8: 'Soporta múltiples divisas legales y gestión de activos digitales.',
            9: 'Gestiona tus activos',
            10: 'Retirada',
            11: '1. La tarjeta bancaria de GoodPago puede extraer moneda local en cajeros automáticos de todo el mundo;',
            12: '2. La moneda digital también se puede cobrar a otras carteras generales a través del terminal móvil o a través de la red principal. Streaming de moneda digital convierte retiros de moneda legal.',
            13: 'Moneda francesa y cambio de moneda',
            14: '1. GoodPago no solo es compatible con el intercambio de la moneda legal principal del mundo, sino que también es compatible con las figuras principales. Intercambio entre monedas u otras y monedas digitales y principales monedas;',
            15: '2. El intercambio de activos digitales desarrollado por GoodPago puede realizar fácilmente todo tipo de productos digitales convencionales. Intercambio entre monedas.',
            16: 'Transferencia',
            17: 'Los usuarios de GoodPago pueden transferir dinero fácil y rápidamente a otros usuarios en cualquier momento y en cualquier lugar.',
            18: 'Recarga',
            19: "GoodPago admite la recarga en tiempo real de comercios de POS fuera de línea, transferencia bancaria en línea, recarga de cajero automático, recarga de conveniencia, tarjeta de crédito, Alipay, WeChat y UnionPay recarga a tiempo para una llegada segura.",
            20: 'Pago de compras',
            21: "Los usuarios de GoodPago pueden pagar por móvil, POS, tarjeta bancaria, etc. Método de pago, pague en cualquier momento a los comerciantes en línea y fuera de línea.",
            22: 'Tecnología de nivel superior TPS',
            23: 'El TPS de GoodPago es más alto que los productos actuales y puede manejar hasta 10018 mensajes diferentes por segundo. Al mismo tiempo, con el avance de la tecnología, el TPS de FEDPAGO también aumentará.',
            24: 'GoodPago pago rápido y transferencia',
            25: ' Las funciones de pago y transferencia de GoodPago se basan en la última tecnología de blockchain y se pueden usar en menos de 3 segundos. Los pagos y recibos son mucho más rápidos que otras tecnologías de cadena pública de blockchain y fondos seguros.',
            26: 'Gestion de activos',
            27: 'Los usuarios de GoodPago descentralizan la administración a través de blockchain para asegurar los activos de los usuarios',
            28: 'Autenticación mutua de alto pago',
            29: 'Los usuarios de GoodPago deben autenticarse entre sí cuando realizan pagos altos. Cuando un teléfono móvil necesita pagar una gran cantidad de dinero, debe usar una tarjeta para autenticarse. Cuando se usa una tarjeta para pagar, se requiere autenticación de teléfono móvil para proteger la seguridad de los activos del usuario. ',
            30: 'Nueva ecología crediticia.',
            31: 'Credito personal',
            32: 'Los usuarios de GoodPago pueden disfrutar del depósito sin cargo, ropa, alojamiento, viajes, etc. en la ecología del crédito. Los servicios gratuitos pre-existentes, pre-test y post-venta hacen que el crédito sea valioso. ',
            33: 'Crédito corporativo',
            34: 'GoodPago establece un sistema de informes de crédito para empresas, comerciantes y socios para medir valor por valor El riesgo crediticio de la industria ayuda a las empresas, empresas y empresas a establecer un ecosistema empresarial de alta calidad. ',
            35: 'Servicio de taxi',
            36: 'GoodPago proporciona una plataforma de viaje de una sola parada',
            37: 'El seguro',
            38: 'Establecimiento de la cadena de suministro de seguros, ecología financiera a través de blockchain.',
            39: 'El intercambio',
            40: 'Acceso a las principales API de intercambio para cumplir con las transacciones y la gestión de activos digitales de los usuarios',
            41: 'Sobre rojo',
            42: 'Envía sobres rojos, dibuja tú y yo.',
            43: 'Boletaje electronico',
            44: 'No es necesario hacer cola para recoger todo tipo de facturas directamente a la nube para enviar tickets ',
            45: 'Cupon electronico',
            46: 'No es necesario conservar el vale de la entidad.',
            47: 'Donacion',
            48: 'Servicio de ventanilla única para la visualización, donación y comentarios de proyectos de bienestar público.',
            49: 'Servicios financieros',
            50: 'Proporcionar servicios de valor agregado a la gestión de activos financieros.'
        },
    },
    home: {
        cn: {
            f_t: '链接世界，数字支付',
            f_subt: 'DARÍA以每个人为中心，以实名和信任为基础的区块链一站式场景平台',
            f_qr_login: '扫码登录',
            f_download: '下载GoodPago APP',

            s_c: '商业合作',
            s_t_c: 'GoodPago推广合作',
            s_s_c: '收钱码合作',
            s_z_c: '支付系统合作',
            s_y_h: '银行收单服务',
            s_g_g: '各国支付接入',
            s_c_w: '成为GoodPago服务商',
            s_h_y: '行业合作',
            s_n_s: '零售',
            s_d_c: '打车',
            s_c_s: '城市服务',
            s_y_n: '医疗',
            s_g_d: '更多行业方案',

            s_k_s: '快速开发',
            s_k_f: '开发接入',
            s_z_f: '支付接入、行业应用模板、API开放',
            s_x_c: '小程序',
            s_x_d: '新的开发能力，更出色的使用体验',
            s_s_h: '生活号',
            s_t_g: '提供代入驻能力，帮助商户提高运营能力',

            f_kfnl: '开放能力版图',
            f_zfnl: '支付能力',
            f_mzsh: '满足商户各商业经营场景的收单需求',
            f_fp: '发票',
            f_shks: '商户快速开发发票，用户便捷管理发票',
            f_yxnl: '营销能力',
            f_yxtg: '营销推广必备利器',
            f_xytx: '信用体系',
            f_shgx: '商户高效识别用户真实性、可靠性',
            f_hyyx: '会员营销',
            f_yyhy: '运营会员并提升会员粘性',
            f_jrkj: '金融科技',
            f_djjy: '对接交易所API让用户一站式投资',
            f_aqbz: '安全保障',
            f_fxaq: '分享安全能力，防范黑产共计',
            f_szhb: '数字货币支付',
            f_kycy: '可以采用可累数字货币支付、结算',
            f_good: 'GoodPago和生态货币一起在全球服务',
            f_qqyh: '全球用户',
            f_shzy: '商户资源',
            f_ydar: '与DARÍA共享生态资源',
            f_zlqq: '链接全球',
            f_sxqq: '实现全球区块链项目落地',
            // f_:'产品介绍',
            // f_:'商户资源',
            // f_:'商户资源',
        },
        en: {
            f_t: 'Connect The World Digital Payment'
        }
    }
}

function getQueryString(name) {
    var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)", "i");
    var r = window.location.search.substr(1).match(reg);
    if (r != null) return unescape(r[2]); return null;
}
const config = {
    urlLang: getQueryString('lang'),
    defaultLang: 'sp',
}
function initApp(path) {
    window.app = new Vue({
        el: '#app',

        data: {
            isLayerVisible: false,
            nav: language.nav[config.urlLang] || language.nav[config.defaultLang],
            lang: language[path][config.urlLang] || language[path][config.defaultLang]
        },
        methods: {
            toggleLayer() {
                this.isLayerVisible = !this.isLayerVisible;
            },
            setLang() {
                this.nav = language.nav[lang] || language.nav[defaultLang];
                this.lang = language[path][lang] || language[path][defaultLang];
            }
        },
    });
};
