var language = {
    home: {
        cn: {
            f_t: '链接世界，数字支付',
            f_subt: 'DARÍA以每个人为中心，以实名和信任为基础的区块链一站式场景平台',
            f_qr_login: '扫码登录',
            f_download: '下载GoodPago APP',

            s_c: '商业合作',
            s_t_c: 'GoodPago推广合作',
            s_s_c: '收钱码合作',
            s_z_c: '支付系统合作',
            s_y_h: '银行收单服务',
            s_g_g: '各国支付接入',
            s_c_w: '成为GoodPago服务商',
            s_h_y: '行业合作',
            s_n_s: '零售',
            s_d_c: '打车',
            s_c_s: '城市服务',
            s_y_n: '医疗',
            s_g_d: '更多行业方案',

            s_k_s: '快速开发',
            s_k_f: '开发接入',
            s_z_f: '支付接入、行业应用模板、API开放',
            s_x_c: '小程序',
            s_x_d: '新的开发能力，更出色的使用体验',
            s_s_h: '生活号',
            s_t_g: '提供代入驻能力，帮助商户提高运营能力',

            f_kfnl: '开放能力版图',
            f_zfnl: '支付能力',
            f_mzsh: '满足商户各商业经营场景的收单需求',
            f_fp: '发票',
            f_shks: '商户快速开发发票，用户便捷管理发票',
            f_yxnl: '营销能力',
            f_yxtg: '营销推广必备利器',
            f_xytx: '信用体系',
            f_shgx: '商户高效识别用户真实性、可靠性',
            f_hyyx: '会员营销',
            f_yyhy: '运营会员并提升会员粘性',
            f_jrkj: '金融科技',
            f_djjy: '对接交易所API让用户一站式投资',
            f_aqbz: '安全保障',
            f_fxaq: '分享安全能力，防范黑产共计',
            f_szhb:'数字货币支付',
            f_kycy:'可以采用可累数字货币支付、结算',
            f_good:'GoodPago和生态货币一起在全球服务',
            f_qqyh:'全球用户',
            f_shzy:'商户资源',
            f_ydar:'与DARÍA共享生态资源',
            f_zlqq:'链接全球',
            f_sxqq:'实现全球区块链项目落地',
            // f_:'产品介绍',
            // f_:'商户资源',
            // f_:'商户资源',
        },
        en: {
            f_t: 'Connect The World Digital Payment'
        }
    }
}